apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: kotannithin/calculator-web:1.0.0
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 8080       # internal service port
      targetPort: 8080 # container port
      nodePort: 30007  # external port (fixed)
